version: '3.8'

services:

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: compose/Dockerfile.nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

  web:
    container_name: web
    build:
      context: ./
      dockerfile: compose/Dockerfile.django
    command: gunicorn Pokemons.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - compose/env/.env.prod
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pokemons

volumes:
  static_volume:
  postgres_data:



